[customizations.installer.kickstart]
contents = """
"""

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Localization",
    "org.fedoraproject.Anaconda.Modules.Timezone"
]
